# .bashrc.d/bashrc
# /* vim: set filetype=rc : */

if [ "$(command -v eza)" ]; then
  alias lla='eza -la --icons=auto --group-directories-first'
fi

if [ "$(command -v bws)" ]; then
  source <(bws completions bash)
fi

if [ "$(command -v tea)" ]; then
  if ! [ -f "$HOME/.config/tea/autocomplete.sh" ]; then
    tea autocomplete bash 2>&1 >/dev/null
  fi
  PROG=tea source "$HOME/.config/tea/autocomplete.sh"
fi

# set bash completion to be more fuzzy.
# bind 'set completion-ignore-case on'

# Set my $EDITOR to nvim or vim.
#if [ "$(command -v nvim)" ]; then
#  export EDITOR="nvim"
if ! [ "$(command -v vim)" ]; then
  export EDITOR="nano"
else
  export EDITOR="vim"
fi

# Set up Node Version Manager if installed
if [ -f "$HOME/.config/nvm/nvm.sh" ]; then
    export NVM_DIR="$HOME/.config/nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
fi

# Set up Virtualenvwrapper
[ -f "/usr/share/virtualenvwrapper/virtualenvwrapper.sh" ] && \
    export WORKON_HOME="$HOME/.local/share/virtualenvs" && \
    \. /usr/share/virtualenvwrapper/virtualenvwrapper.sh

# Added by Toolbox App
if [[ -d "$HOME/.local/share/JetBrains/Toolbox/scripts/" ]] ; then
  export PATH="$PATH:$HOME/.local/share/JetBrains/Toolbox/scripts"
fi

# Ensure proper locale
export LC_ALL=en_CA.UTF-8
export LANG=en_CA.UTF-8

# Set tmux tmpdir when in a distrobox
if [[ -n $CONTAINER_ID ]]; then
  export TMUX_TMPDIR=/tmp/tmux-${CONTAINER_ID}-1000
fi

# Set GOPATH if it exists
if [[ -d $HOME/go ]]; then
  export GOPATH="$HOME/go"
  export GOBINDIR="$GOPATH/bin"
  export PATH="$PATH:$GOPATH/bin"
fi

# Add terraform completions
[ "$(command -v terraform)" ] && eval "$(complete -C /usr/bin/terraform terraform)"

# Debian Packager info
export DEBEMAIL='john@schmidthaus.rocks'
export DEBFULLNAME='John Schmidt'
export GPGKEY=729F6BE4A82641BC
