# .bashrc.d/bashrc
# /* vim: set filetype=rc : */

if [ "$(command -v eza)" ]; then
  alias lla='eza -la --icons=auto --group-directories-first'
fi

if [ "$(command -v bws)" ]; then
  source <(bws completions bash)
fi

if [ "$(command -v tea)" ]; then
  if ! [ -f "$HOME/.config/tea/autocomplete.sh" ]; then
    tea autocomplete bash 2>&1 >/dev/null
  fi
  PROG=tea source "$HOME/.config/tea/autocomplete.sh"
fi

# set bash completion to be more fuzzy.
# bind 'set completion-ignore-case on'

if [ "$(command -v direnv)" ]; then
  eval "$(direnv hook bash)"
fi

# Set my $EDITOR to nvim or vim.
#if [ "$(command -v nvim)" ]; then
#  export EDITOR="nvim"
if ! [ "$(command -v vim)" ]; then
  export EDITOR="nano"
else
  export EDITOR="vim"
fi

# Set up Node Version Manager if installed
if [ -f "$HOMEBREW_PREFIX/opt/nvm/nvm.sh" ]; then
  NVM_DIR="$HOME/.local/share/nvm"
  if [ ! -d $NVM_DIR ]; then
    mkdir -p $NVM_DIR
  fi
  export NVM_DIR
  # This loads nvm
  [ -s "$HOMEBREW_PREFIX/opt/nvm/nvm.sh" ] && \. "$HOMEBREW_PREFIX/opt/nvm/nvm.sh"
  # This loads nvm bash_completion
  [ -s "$HOMEBREW_PREFIX/opt/nvm/etc/bash_completion.d/nvm" ] && \. "$HOMEBREW_PREFIX/opt/nvm/etc/bash_completion.d/nvm"
fi

# Set up Virtualenvwrapper
if [ "$(command -v virtualenvwrapper.sh)" ]; then
  export WORKON_HOME="$HOME/.local/share/virtualenvs"
  source virtualenvwrapper.sh
fi

# Added by Toolbox App
if [[ -d "$HOME/.local/share/JetBrains/Toolbox/scripts/" ]] ; then
  export PATH="$PATH:$HOME/.local/share/JetBrains/Toolbox/scripts"
fi

# Ensure proper locale
export LC_ALL=en_CA.UTF-8
export LANG=en_CA.UTF-8

# Set tmux tmpdir when in a distrobox
if [[ -n $CONTAINER_ID ]]; then
  export TMUX_TMPDIR=/tmp/tmux-${CONTAINER_ID}-1000
fi

# Set GOPATH if it exists
if [[ -d $HOME/go ]]; then
  export GOPATH="$HOME/go"
  export GOBINDIR="$GOPATH/bin"
  export PATH="$PATH:$GOPATH/bin"
fi
